### ISSUE TITLE
Deleting instances in AWS

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk#69] opened 2018-11-16 19:03 UTC
If AWS cluster teardown fails, users might find themselves trying to delete EC2 instances manually. Sometimes, they just keep respawning themselves, since they're part of an autoscaling group. We should include documentation on how to deal with this in the troubleshooting document. More generally, it might be a good idea to document the entire process of deleting a cluster manually.

**Comment by dylanbannon** [comment] 2018-11-16 19:07
we also need to delete launch configurations

**Comment by osterman** [comment] 2018-11-16 19:08
See: https://github.com/kubernetes/kops/issues/3353#issuecomment-328774306


Shy of this, I think it would require a shell script that iterates over all the possible resources looking for those tagged with the specific cluster name. Then deleting them. It would be a bit painful.

**Comment by willgraf** [comment] 2019-08-17 03:41
Closing this as the issue is now being tracked by #169.

**Closed by willgraf** 2019-08-17 03:41 UTC
Labels: enhancement
